default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: thants
  host: localhost

development:
  <<: *default
  database: schools

test:
  <<: *default
  database: school_tests

production:
  <<: *default
  database: school_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
